### PR TITLE
[Doc] fixing typos and errors

### PR DESCRIPTION
**Pull request by Holladiewal**

### CODE REVIEW

**Review by Eearslya — DISMISSED** [review]

**Comment by theunkn0wn1** [comment]
the code quality link is null, it can be safely removed.

The coverage link can be updated to coverage's badge, 
```md


[![codecov](https://codecov.io/gh/FuelRats/pipsqueak3/branch/develop/graph/badge.svg)](https://codecov.io/gh/FuelRats/pipsqueak3)


```

For some reason coverage is not reporting on your PR, did you break something?

**Comment by Eearslya** [comment]
I think coverage is not reporting because nothing was committed that is handled by codecov. You can see the coverage report did complete successfully, but it only included files that it doesn't care about.

https://codecov.io/github/beepbeat/pipsqueak3/commit/dfdb01ea1928ec4e7938813762080ec25befe65c

**Review by theunkn0wn1 — CHANGES_REQUESTED** [review]
please update against upstream/develop.(request No, 2)

**Review by theunkn0wn1 — APPROVED** [review]
LGTM

**Pull request merged**
