### PR TITLE
Add poetry-flavor pyproject.toml

### PR DESCRIPTION
**Pull request by theunkn0wn1**
Welp, turns out Pipenv is pretty darn broken on Windows in py3.8, now is as good a time as any to switch to something that will allow us to eventually package this project into a wheel.

to obtain a devel environment:
`poetry install -d`
to activate the virtual environment:
`poetry shell`

to get the wheel:
`poetry build`

### CODE REVIEW

**Review by shatteredbeam — COMMENTED** [review]
The last time I saw a PR this good, someone was removing the turbo button from the front of a PC.

**Review by shatteredbeam — DISMISSED** [review]

**Comment by theunkn0wn1** [comment]
build failures are to be expected, i need to fix CI since it still uses pipenv...

**Review by Eearslya — APPROVED** [review]
Coverage weirdness can be sorted out later. As this is a mission-critical fix, approved.

**Comment by theunkn0wn1** [comment]
Thanks. Il do a follow up PR later to fix the documentation and see if i can figure out how we broke coverage as this PR is mission-critical.

@shatteredbeam to get you going locally:
```bash
git clone ... -b develop

poetry install --no-root
poetry shell
```
poetry will spit out a `venv` for you, just tell PyCharm to use that venv interpreter. Let me know if you have any issues with this.

**Pull request merged**
